name: Deploy Geneconnect AWS Infra

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI
    inputs:
      Region:
        description: "AWS Region to deploy the infrastructure :"
        required: true
        type: choice
        default: "ap-northeast-3"
        options:
          - us-east-1    # N. Virginia
          - us-east-2    # Ohio
          - us-west-1    # N. California
          - us-west-2    # Oregon
          - ap-south-1   # Mumbai
          - ap-northeast-3 # Osaka
          - ap-northeast-2 # Seoul
          - ap-southeast-1 # Singapore
          - ap-southeast-2 # Sydney
          - ap-northeast-1 # Tokyo
          - ca-central-1 # Canada Central
          - eu-central-1 # Frankfurt
          - eu-west-1    # Ireland
          - eu-west-2    # London
          - eu-west-3    # Paris
          - eu-north-1   # Stockholm
          - sa-east-1    # São Paulo

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check AWS CLI version
        run: |
          sudo apt update
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ github.event.inputs.Region }}   # Change to your desired region

      - name: Run Deployment Script
        working-directory: CreateStack
        run: |
          chmod +x deploy-infra.sh
          ./deploy-infra.sh "${{ github.event.inputs.Region }}"

      - name: Wait for CloudFormation Completion
        run: |
          STACK_NAME="geneconnect-stack"
          REGION="${{ github.event.inputs.Region }}"
          
          echo "Waiting for CloudFormation stack '$STACK_NAME' to complete..."
          aws cloudformation wait stack-create-complete \
            --stack-name $STACK_NAME \
            --region $REGION
          echo "Stack creation complete."

      - name: Upload PEM Key as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geneconnect-key
          path: CreateStack/geneconnect-key.pem  # Update this if your script outputs it elsewhere
      
      - name: Fetch Outputs from CloudFormation
        id: cfn
        run: |
          STACK_NAME="geneconnect-stack"
          REGION="${{ github.event.inputs.Region }}"
          
          EIP=$(aws cloudformation describe-stacks \
            --region $REGION \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" \
            --output text)

          echo "Elastic IP: $EIP"
          echo "EIP=$EIP" >> $GITHUB_ENV

      - name: Download Docker Compose Plugin
        run: |
          chmod 400 CreateStack/geneconnect-key.pem
          ssh -o StrictHostKeyChecking=no -i CreateStack/geneconnect-key.pem ubuntu@$EIP <<EOF

            echo "Installing Docker Compose plugin"
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl vim
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o docker.asc
            sudo mv docker.asc /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \$(. /etc/os-release && echo \${UBUNTU_CODENAME:-\${VERSION_CODENAME}}) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
          EOF


      