name: Delete Geneconnect AWS Infra 

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI
    inputs:
      confirm_delete:
        description: "Are you sure you want to delete the Geneconnect AWS infrastructure?)"
        required: true
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"
      Region:
        description: "AWS Region to Delete the infrastructure :"
        required: true
        type: choice
        default: "ap-northeast-3"
        options:
          - us-east-1    # N. Virginia
          - us-east-2    # Ohio
          - us-west-1    # N. California
          - us-west-2    # Oregon
          - ap-south-1   # Mumbai
          - ap-northeast-3 # Osaka
          - ap-northeast-2 # Seoul
          - ap-southeast-1 # Singapore
          - ap-southeast-2 # Sydney
          - ap-northeast-1 # Tokyo
          - ca-central-1 # Canada Central
          - eu-central-1 # Frankfurt
          - eu-west-1    # Ireland
          - eu-west-2    # London
          - eu-west-3    # Paris
          - eu-north-1   # Stockholm
          - sa-east-1    # São Paulo
        

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check AWS CLI version
        run: |
          sudo apt update
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-3   # Change to your desired region

      - name: Run Delete Stack Script
        working-directory: DeleteStack
        if: ${{ github.event.inputs.confirm_delete == 'yes' }}
        run: |
          chmod +x delete-infra.sh
          ./delete-infra.sh "${{ github.event.inputs.Region }}"
